sudo: false
language: node_js
node_js:
  - 4
services:
  - docker
notifications:
  email: false
before_install:
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine
install:
  - npm install -g npm@"$(jq -r '.engines.npm' package.json)"
  - npm install
script:
  - npm test
after_success:
  - semantic-release
