editor:
  environment:
    ENVIRONMENT: ${environment}
    API__HOST: http://server.${base_host}
  labels:
    traefik.domain: ${domain}
    traefik.port: '9000'
    traefik.enable: 'true'
  image: ${editor_image}

server:
  environment:
    ENVIRONMENT: ${environment}
    db__host: postgres
    search__host: http://elasticsearch:9200
  labels:
    traefik.domain: ${domain}
    traefik.port: '9090'
    traefik.enable: 'true'
  command:
    - bash
    - -c
    - grunt setup --first_name=dummy --last_name=dummy --email=dev@livingdocs.io --password=${environment} --project_name=livingdocs --design_name=timeline --design_version=0.6.2 && node index.js
  image: ${server_image}
  links:
  - elasticsearch:elasticsearch
  - postgres:postgres

postgres:
  image: livingdocs/postgres:latest

elasticsearch:
  image: livingdocs/elasticsearch:latest
