editor:
  environment:
    ENVIRONMENT: ${environment}
    API__HOST: http://server.${base_host}
  labels:
    traefik.domain: ${domain}
    traefik.port: '9000'
    traefik.enable: 'true'
  image: ${editor_image}

server:
  environment:
    ENVIRONMENT: ${environment}
    db__host: postgres
    db__database: ${base_host}
    search__host: http://elasticsearch:9200
    search__article_document_index: ${base_host}
  labels:
    traefik.domain: ${domain}
    traefik.port: '9090'
    traefik.enable: 'true'
  command:
    - bash
    - -c
    - grunt setup --first_name=dummy --last_name=dummy --admin --token_based_signup --email=dev@livingdocs.io --password=${environment} --project_id --design_name=timeline --design_version=0.8.0 && node index.js
  image: ${server_image}
  external_links:
    - Services/elasticsearch
    - Services/postgres
