# This file is managed with https://github.com/upfrontIO/livingdocs-docker
# Local changes are discouraged as they might get overwritten

version: '2'
services:
  editor:
    command: ["npm", "start"]
    build:
      context: .
      args:
        - ENVIRONMENT=local
        - SKIP_BUILD=true
    ports:
      - 9000:9000
